export const ADD_USER_API_SAGA = "ADD_USER_API_SAGA";
export const GET_ALL_USER_API_SAGA = "GET_ALL_USER_API_SAGA";
export const SET_ALL_USER_REDUCER = "SET_ALL_USER_REDUCER";
export const SET_DETAIL_USER_REDUCER = "SET_DETAIL_USER_REDUCER";
export const SET_NEW_USER_REDUCER = "SET_NEW_USER_REDUCER";
export const GET_DETAIL_USER_API_SAGA = "GET_DETAIL_USER_API_SAGA";